<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getListQueryBuilder()
    {
        $qb = $this->createQueryBuilder('albumRepository');

        $qb->addOrderBy('albumRepository.id', 'DESC');

        return $qb;
    }

    public function getListWithImageMinQueryBuilder($maxCountImages)
    {
        $qb = $this->createQueryBuilder('albumRepository');

        $qb->andWhere('albumRepository.countImages < (:maxCountImages)')
            ->setParameter('maxCountImages', (int) $maxCountImages, Type::INTEGER)
        ;

        $qb->addOrderBy('albumRepository.id', 'DESC');

        return $qb;
    }

    public function getById($id)
    {
        if (null === $id) {
            return null;
        }

        $qb = $this->createQueryBuilder('albumRepository');

        $qb->andWhere('albumRepository.id = (:id)')
            ->setParameter('id', (int) $id, Type::INTEGER)
        ;

        $qb->leftJoin('albumRepository.images', 'images')
            ->addSelect('images')
        ;

        return $qb->getQuery()->getResult();
    }
}
